<?php

// Load Nette Framework or autoloader generated by Composer
require __DIR__ . '/../libs/composer/autoload.php';

$configurator = new Nette\Config\Configurator;

// Enable Nette Debugger for error visualisation & logging
//$configurator->setDebugMode(FALSE);
$configurator->enableDebugger(__DIR__ . '/../log');

// Enable RobotLoader - this will load all classes automatically
$configurator->setTempDirectory(__DIR__ . '/../temp');
$configurator->createRobotLoader()
    ->addDirectory(__DIR__)
    ->addDirectory(__DIR__ . '/../libs')
    ->register();

// Create Dependency Injection container from config.neon file
$configurator->addConfig(__DIR__ . '/setup/config.neon');
$configurator->addConfig(__DIR__ . '/setup/config.local.neon', $configurator::NONE); // none section
$container = $configurator->createContainer();

$container->application->onRequest[] = function ($application, $request) {
    QOP\Application\SetErrorPresenter::setErrorPresenter($application, $request);
};

return $container;
